const statNames = {
    bullet: 0,
    smasher: 1,
    drone: 2,
    necro: 3,
    swarm: 4,
    trap: 5,
    generic: 6,
    autoSmash: 7,
    minion: 8,
    jumpSmash: 9,
    block: 10,
    boomer: 11,
    lancer: 12,
    flail: 13,
    inject: 14,
    laser: 15,
    aura: 16,
    shield: 17,
    navi: 18,
    fovIncrease: 19,
    baller: 20,
    triTrap: 21,
    airstrike: 22 
};
const gunCalcNames = {
    default: 0,
    bullet: 1,
    drone: 2,
    swarm: 3,
    fixedReload: 4,
    thruster: 5,
    sustained: 6,
    necro: 7,
    trap: 8,
    aura: 9,
    ball: 10,
    block: 11,
    strike: 12,
    fire: 13,
    worm: 14,
    atk_smasher: 15,
    kami: 16,
    wreck: 17,
    tesla_aura: 18 
}
const colors = {
    // for extra entity colors 
    milk: ("#F0EBC5"),
    blueVio: ("#5800DB"),
    shit: ("#694120"),
    deflect: ("#FFE100"),
    frozen: ("#7FFFFF"),
    poisoned: ("#C0FF80"),
    swollen: ("#BF80FF"),
    relapsed: ("#FF80C0"),
    bitten: ("#800000"),
    electro: ("#0000FF"),
    crown: ("#D69A24"),
    kazam: ("#BF40BF"),
    starving: ("#202060"),
    noro: ("#8BC8AF"),
    undef: ("#A2D8B4"),
    lantern: ("#3B3F39"),
    spectral: ("#78736D"),
    weak: ("#ADE57F"),
    stupid: ("#9FC1E8"),
    extraRed: ("#F22639"),
    urti: ("#8CAED2"),
    irri: ("#CD82BC"),
    unity: ("#ADA7CD"),
    aus: ("#606020"),
    bolt: ("#FFCE00"),
    droplet: ("#08A3FC"),
    value: ("#E7CD44"),
    wood: ("#C19A6B"),
    delin: ("#B7ABA1"),
    tele: ("#AC65B8"),
    squall: ("#FFC971"),
    gust: ("#DDC092"),
    sound: ("#63E291"),
    mage: ("#9476C4"),
    loft: ("#99FFC7"),
    amalgam: ("#5A574D"),
    acacia: ("#74502F"),
    fruitTree: ("#7C5F46"),
    misfit: "#004080"
};
const base = {
    ACCEL: 1,
    SPEED: 5,
    HEALTH: 170,
    DAMAGE: 4,
    RESIST: 1,
    PENETRATION: 2,
    SHIELD: 5,
    REGEN: .05,
    DENSITY: 2,
    FOV: 1.2,
    PUSHABILITY: .7,
    HETERO: 3.75,
    DAMP: 1,
    SHOCK_ABSORB: 1
};
base.ACCELERATION = base.ACCEL;
base.SHOCK = base.SHOCK_ABSORB;
base.PUSH = base.PUSHABILITY;
base.PEN = base.PENETRATION;

export { statNames, gunCalcNames, colors, base }