let maps = [{
        "WIDTH": 6900,
        "HEIGHT": 6900,
        "MODE": "tdm",
        "serverName": "Boss Rush",
        "TEAM_AMOUNT": 1,
        "BOSS_SPAWN_TIMER": Infinity,
        "ROOM_SETUP": [
            ["outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb"],
			["outb", "outb", "bas2", "bas2", "bas2", "bas2", "bas2", "outb", "outb"],
			["outb", "bas2", "nest", "nest", "nest", "nest", "nest", "bas2", "outb"],
			["outb", "bas2", "nest", "nest", "tree", "nest", "nest", "bas2", "outb"],
			["outb", "bas2", "nest", "tree", "bas1", "tree", "nest", "bas2", "outb"],
			["outb", "bas2", "nest", "nest", "tree", "nest", "nest", "bas2", "outb"],
			["outb", "bas2", "nest", "nest", "nest", "nest", "nest", "bas2", "outb"],
			["outb", "outb", "bas2", "bas2", "bas2", "bas2", "bas2", "outb", "outb"],
			["outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb"]
		],
        "X_GRID": 9,
        "Y_GRID": 9,
        "PLAYER_SPAWN_TILES": ["bas1", "tree"],
        "BOT_SPAWN_TILES": ["bas1", "tree"],
        "MAX_FOOD": 16,
        "MAX_NEST_FOOD": 4,
        "MAX_CRASHERS": 60,
        "MAX_SANCS": 0,
		"OUTSIDE_ROOM_DAMAGE": 50000,
		"ZONES": "nest woods",
        "ISSIEGE": true  
}, {
        "WIDTH": 5400,
        "HEIGHT": 5400,
        "MODE": "tdm",
        "serverName": "Boss Rush",
        "TEAM_AMOUNT": 1,
        "BOSS_SPAWN_TIMER": Infinity, 
        "ROOM_SETUP": [
            ["deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep"],
            ["deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep"],
		    ["deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep"],
		    ["watr", "watr", "watr", "watr", "watr", "watr", "watr", "watr", "watr"],
		    ["bas2", "watr", "watr", "watr", "watr", "watr", "watr", "watr", "bas2"],
		    ["bas2", "norm", "norm", "norm", "bas1", "norm", "norm", "norm", "bas2"],
		    ["bas2", "watr", "watr", "watr", "watr", "watr", "watr", "watr", "bas2"],
		    ["watr", "watr", "watr", "watr", "watr", "watr", "watr", "watr", "watr"],
		    ["deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep"],
            ["deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep"],
            ["deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep", "deep"]
        ],
        "X_GRID": 9,
        "Y_GRID": 11,
        "PLAYER_SPAWN_TILES": ["bas1"],
		"BOT_SPAWN_TILES": ['bas1'],
        "MAX_FOOD": 0,
        "MAX_NEST_FOOD": 0,
        "MAX_CRASHERS": 0,
	    "MAX_FISH": 150,
	    "MAX_AQUA_FOOD": 200,
        "MAX_SANCS": 0,
        "DO_BASE_DAMAGE": true,
        "MAX_AMALGAMS": 0,
        "ZONES": "water",
        "ISSIEGE": true 
}]
maps[Math.floor(Math.random() * maps.length)];