let maps = [{
        "WIDTH": 6500,
        "HEIGHT": 6500,
        "MODE": "tdm",
        "serverName": "Tag",
        "TEAM_AMOUNT": Math.floor(Math.random() * 2 + 2),
        "BOSS_SPAWN_TIMER": 130, 
        "ROOM_SETUP": [
            ["rock", "rock", "norm", "norm", "norm", "rock", "rock"],
            ["rock", "rock", "norm", "norm", "norm", "rock", "rock"],
            ["norm", "norm", "tree", "tree", "tree", "norm", "norm"],
            ["norm", "norm", "tree", "watr", "tree", "norm", "norm"],
            ["norm", "norm", "tree", "tree", "tree", "norm", "norm"],
            ["rock", "rock", "norm", "norm", "norm", "rock", "rock"],
            ["rock", "rock", "norm", "norm", "norm", "rock", "rock"],
        ],
        "X_GRID": 7,
        "Y_GRID": 7,
        "PLAYER_SPAWN_TILES": ["norm"],
        "BOT_SPAWN_TILES": ["norm"],
        "MAX_FOOD": 80,
		"MAX_FISH": 7,
        "MAX_ROID_FOOD": 18,
        "MAX_AMALGAMS": 6,
        "ZONES": "rock woods water"
}, {
    "MODE": "tdm",
    "serverName": "Tag",
    "TEAM_AMOUNT": Math.floor(Math.random() * 2 + 2),
    "BOSS_SPAWN_TIMER": 130,
    "MAZE": {
        "ENABLED": true,
        "cellSize": 184,
        "stepOneSpacing": .7,
        "fillChance": .3,
        "sparedChance": .9,
        "cavey": false,
        "lineAmount": false,
        "margin": 0,
        "posMulti": 0,
        "MAGIC": false 
    },
    "WIDTH": 6500,
    "HEIGHT": 6500,
    "ROOM_SETUP": [
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "rock", "rock", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "rock", "rock", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
        ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"]
    ],
    "X_GRID": 18,
    "Y_GRID": 18,
    "FOOD_AMOUNT": 13,
}];
maps[Math.floor(Math.random() * maps.length)];