let maps = [{
        "WIDTH": 7300,
        "HEIGHT": 6200,
        "MODE": "tdm",
        "serverName": "Assault",
        "TEAM_AMOUNT": 2,
        "BOSS_SPAWN_TIMER": Infinity, 
        "ROOM_SETUP": [
            ["roid", "roid", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "roid", "roid"], 
            ["roid", "roid", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "roid", "roid"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "wall", "wall", "dont", "wall", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "wall", "dom2", "wall", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "wall", "wall", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "wall", "wall", "wall", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dom2", "wall", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "wall", "dom2", "dont", "dont", "wall", "wall", "dont", "wall", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "wall", "wall", "wall", "dont", "dont", "dont", "dont", "wall", "wall", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "wall", "wall", "dont", "dont", "dom2", "dont", "wall", "dont", "dont", "dont", "wall", "dont", "dont", "wall", "nest", "nest", "nest", "wall", "dont", "dont", "wall", "dont", "dont", "wall", "dont", "dont", "dont", "dont"], 
            ["dont", "dont", "dont", "dont", "wall", "dont", "wall", "dont", "dont", "wall", "wall", "wall", "dom2", "dont", "dont", "nest", "nest", "nest", "nest", "nest", "wall", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "wall", "dont", "dont", "wall", "dont", "dont", "dont", "wall", "dont", "wall", "wall", "wall", "nest", "nest", "nest", "nest", "wall", "wall", "dont", "wall", "dont", "dont", "dont", "wall", "dont", "dont"],
            ["dont", "dont", "dont", "wall", "dont", "dont", "dont", "wall", "wall", "dont", "dont", "dont", "dont", "dont", "nest", "nest", "nest", "nest", "nest", "wall", "dont", "dont", "dont", "dont", "wall", "dont", "wall", "wall", "dont", "dont"],
            ["dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "tree", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "wall", "dont", "dont", "dont"],
            ["dont", "dont", "wall", "wall", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "wall", "dont", "dont", "tree", "tree", "wall", "wall", "dont", "dont", "dont", "wall", "wall", "dont", "wall", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "wall", "dom2", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "tree", "tree", "tree", "wall", "dom2", "wall", "wall", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "wall", "wall", "wall", "wall", "dont", "dont", "dont", "wall", "dont", "tree", "wall", "tree", "tree", "tree", "dont", "wall", "dont", "dont", "dont", "wall", "dont", "dont", "wall", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dom2", "dont", "dont", "wall", "tree", "tree", "wall", "tree", "tree", "dont", "wall", "dont", "dont", "dont", "dont", "wall", "dont", "dom2", "wall", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "wall", "wall", "wall", "dont", "tree", "tree", "wall", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "wall", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont"], 
            ["dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "wall", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "dont"],
            ["roid", "roid", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "n_b1", "bas1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "bas1", "n_b1", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "roid", "roid"],
            ["roid", "roid", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "n_b1", "dont", "dont", "dont", "dont", "dont", "dont", "dont", "roid", "roid"]
        ],
        "X_GRID": 30,
        "Y_GRID": 30,
        "BOT_SPAWN_TILES": ["dom1", "dom2"],
        "MAX_FOOD": 25,
        "MAX_NEST_FOOD": 6,
        "MAX_CRASHERS": 17,
        "ASSAULT": true,
        "MAX_AMALGAMS": 10,
		"ZONES": "nest rock woods"
}, {
        "WIDTH": 6400,
        "HEIGHT": 6400,
        "MODE": "tdm",
        "serverName": "Assault",
        "TEAM_AMOUNT": 2,
        "BOSS_SPAWN_TIMER": Infinity, 
        "ROOM_SETUP": [
            ["b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b"],
            ["b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n W n n W n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n W W n n W n W W n n n n n n n n n n n"],
            ["n n n n n n n n n W W n n n n W n n n W W n n n n n n n n n"],
            ["n n n n n n n W W n n n n n W r W W n n n W W n n n n n n n"],
            ["n n n n n n W n n n n n n n n n n n n n W n n W W n n n n n"],
            ["n n n W n n n n W W W n n W W W W n n n n n W r W W n n n n"],
            ["n n W n W W n n n n n n W c c c c c n W W n W n W n n W n n"],
            ["n W n n n n W n W W n W c W W W W c W n n n W n W n n n W n"],
            ["W n W n n W n n n W n n c W W W W c W n n W n n n n W W n W"],
            ["W n n n W n n n n n W W c W W W W c W n W n n W n n W n n W"],
            ["n W n W n n W W n n n W c W W W W c W n n n n n n W n n W n"],
            ["n n W r n n n n W n n n W c c c c W n n n n n W W n n n W n"],
            ["n n n W W n W W W W n n n W W n W n W n n W n n n n n n n n"],
            ["n n n n n W W r n n W W n n n n n n n r W n n W W n n n n n"],
            ["n n n n n n n W W n n n W n n W n n W W W W W n n n n n n n"],
            ["n n n n n n n n n W W n n n W n n n n W W n n n n n n n n n"],
            ["n n n n n n n n n n n W W n W n n W W n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n W W n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"],
            ["n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n"]
        ].map(row => row[0].split(" ").map(cell => {
            switch (cell) {
                case "n": return "norm";
                case "W": return "wall";
                case "b": return "n_b1";
                case "r": return "dom2";
                case "c": return "nest";
                default: throw new TypeError(cell + " is not a valid cell type!")
            }
        })),
        "X_GRID": 30,
        "Y_GRID": 30,
        "BOT_SPAWN_TILES": ["dom1", "dom2"],
        "MAX_FOOD": 25,
        "MAX_NEST_FOOD": 6,
        "MAX_CRASHERS": 17,
        "ASSAULT": true,
        "MAX_AMALGAMS": 10,
		"ZONES": "nest"
}];
maps[Math.floor(Math.random() * maps.length)];