let map = {
        "WIDTH": 6500,
        "HEIGHT": 6500,
        "MODE": "ffa",
        "serverName": "None",
		    /*"displayName": "Misfit's Mod",
		    "displayDesc": "FFA Mode\nFormerly Woomy-IIWG. All tanks and their functions: https://docs.google.com/spreadsheets/d/18LFNF-wteXdPgBICXb-x0CDTL3OvSskjDgTpnSMUsv0/edit?usp=sharing",*/
        "TEAM_AMOUNT": 2,
        "BOSS_SPAWN_TIMER": 97, 
        "PORTALS": {
            "ENABLED": false,
            "TANK_FORCE": 3000,
            "TANK_DAMP": 4000,
            "BOSS_FORCE": 12500,
            "DIVIDER_1": {
                "ENABLED": true,
                "LEFT": 2979,
                "RIGHT": 3521
            },
            "DIVIDER_2": {
                "ENABLED": true,
                "TOP": 2979,
                "BOTTOM": 3521
            }
        },
        "MAZE": {
            "ENABLED": false,
            "cellSize": 150,
            "stepOneSpacing": 3,
            "fillChance": .33,
            "sparedChance": .65,
            "cavey": false,
            "lineAmount": false,
            "margin": 0,
            "posMulti": .25,
            "MAGIC": false 
        },
        "ROOM_SETUP": [
            ["roid", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "rock", "rock", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "roid"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm"],
            ["rock", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "roid", "nest", "nest", "nest", "nest", "roid", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["rock", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "roid", "roid", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "rock"],
            ["rock", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "roid", "roid", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "rock"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "roid", "nest", "nest", "nest", "nest", "roid", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["rock", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock"],
            ["norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
            ["roid", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "rock", "rock", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "roid"]
        ],
        "X_GRID": 18,
        "Y_GRID": 18,
        "PLAYER_SPAWN_TILES": ["norm"],
        "BOT_SPAWN_TILES": ["norm"],
        "MAX_FOOD": 400,
        "MAX_NEST_FOOD": 30,
        "MAX_CRASHERS": 18,
		    "MAX_FISH": 20,
        "MAX_ROID_FOOD": 10,
		    "MAX_AQUA_FOOD": 15,
        "MAX_SANCS": 1,
        "TIME_BETWEEN_SANCS": 900000,
        "EVOLVE_TIME": 90000,
        "EVOLVE_TIME_RAN_ADDER": 210000,
        "EVOLVE_HALT_CHANCE": 0.25,
        "DO_BASE_DAMAGE": true,
		    "ARENA_TYPE": 0,
		    "BORDER_FORCE": .025,
        "ISSIEGE": false,
        "DISABLE_LEADERBOARD": false,
        "BLACKOUT": false,
        "SOCCER": false,
        "SECURE": false,
		    "ASSAULT": false,
        "CANNOT_SHOOT_IN_BASE": false,
        "MAX_AMALGAMS": 10,
		    "ZONES": "nest rock",
}
map
